### ISSUE TITLE
Ability to click on links + Images

### ISSUE THREAD

**Issue by apprehensions** [BetaPictoris/wiki#9]
for example:
![image](https://user-images.githubusercontent.com/47404953/163733307-ea4114cc-009d-4778-ba5b-9efd86c7a7b7.png)

I want to to  see Linus torvalds page. i expect to click on it and it forwards it.

as for images, i suggest [Ueberzug](https://github.com/seebye/ueberzug). [go lib](https://pkg.go.dev/gitlab.com/diamondburned/ueberzug-go)

**Comment by BetaPictoris** [comment]
Looks like images could also be done with [teacup](https://github.com/knipferrc/teacup). I'm currently working on polishing up the UX and looking into using [this bubble](https://github.com/knipferrc/teacup/blob/main/examples/statusbar/statusbar.go). I'll also have to see if Glow can support reading when a link is clicked, if so it shouldn't be too hard to get links to work.

**Comment by BetaPictoris** [comment]
Might also be able to get links to work with [BubbleZone](https://github.com/lrstanley/bubblezone).

**Comment by wael444** [comment]
emmmm

**Comment by BetaPictoris** [comment]
Hey @apprehensions!  I just wanted to apologize to you for leaving this issue open forever, I simply don't have enough time to continue working on this project anymore.  If I end up getting more time in the future I might come back to it, just not at the moment. 

Thank you for the amazing idea!

**Comment by apprehensions** [comment]
I think now in the time this issue was up I've managed to learn go on my own.

Might as well do my own nos
